### ISSUE TITLE
Use SOSL to get all classes with "@isTest" annotation

### ISSUE THREAD

**Issue by apexsutherland** [mbotos/Automated-Testing-for-Force.com#3]
I noticed this code snippet on StackExchange:

http://salesforce.stackexchange.com/a/27597

and thought that could be a great alternative way to find all of the classes with unit tests in them, regardless of whether or not they had "Test" in the name. Perhaps we could change this package to use that approach instead?

**Comment by mbotos** [comment]
Neat idea, Alex. Would also be interesting to compare query and search performance in orgs with a large number of test classes. Want to code it up and submit a pull request?
