### ISSUE TITLE
Take dot out of repo name to allow Quick Deploy button?

### ISSUE THREAD

**Issue by rsoesemann** [mbotos/Automated-Testing-for-Force.com#5]
Since you took down the automatic installer from the Alvorden website I was not able to easily install you great tool into a new org. I tried to add one of [Andrew Fawcetts githubdeploy buttons](https://github.com/afawcett/githubsfdeploy) and PR this back to you but it failed as you have a dot in the repo name.

Would you mind renaming your repos as I don't expect any solution to this issue from https://github.com/afawcett/githubsfdeploy/issues/1?

That would be great.

**Comment by jorge0136** [comment]
I had this error till I added .git to the end of the string.  Try "Automated-Testing-for-Force.com.git".

**Comment by rsoesemann** [comment]
That indeed helped. Thank you @jorge0136 !
